---
# Global hosts
azurehosts:
  hosts:
    devops-vm:
      ansible_host: az-devops

# App servers
appservers:
  hosts:
    devops-vm-app:
      ansible_host: az-devops
      ansible_user: azureuser

# Database servers
dbservers:
  hosts:
    devops-vm-db:
      ansible_host: az-devops
      ansible_user: azureuser