---
# Deploy Spring Boot app with Docker
- hosts: appservers
  become: yes
  tasks:

    # Check Docker
    - name: Check if Docker is installed
      shell: docker --version && docker compose version
      register: docker_version_result
      ignore_errors: true

    # Set fact if Docker exists
    - name: Set Docker installed fact
      set_fact:
        docker_installed: "{{ docker_version_result.rc == 0 }}"

    # Install Docker if missing
    - name: Install Docker if not present
      include_tasks: docker.yaml
      when: not docker_installed

    # Clone Spring project
    - name: "Clone the Spring repository"
      git:
        repo: "https://github.com/skk137/rentEstate2.git"
        dest: "{{ appdir }}"
        version: "{{ branch }}"
        force: yes

    # Update application.properties
    - name: "Populate application.properties"
      lineinfile:
        dest: "{{ appdir }}/src/main/resources/application.properties"
        state: present
        regexp: "^{{item.key}}="
        line: "{{item.key}}={{item.value}}"
      with_items:
        - "{{app.env | dict2items}}"

    # Copy .envfile
    - name: "Copy existing .envfile to appdir"
      shell: cp /home/azureuser/.envfile {{ appdir }}/.envfile
      become: yes

    # Stop old containers
    - name: Tear down existing services
      community.docker.docker_compose_v2:
        project_src: "{{ appdir }}"
        state: absent

    # Build and start new containers
    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: "{{ appdir }}"
        build: always
        state: present
      register: output
      notify: Restart Docker Compose

  handlers:
    # Restart services
    - name: Restart Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ appdir }}"
        state: restarted