    # Install basic packages
    - name: Install basic packages
      apt:
        name: "{{item}}"
        state: present
        update_cache: true
      loop:
        - software-properties-common
        - curl
        - apt-transport-https
        - ca-certificates

    # Add Docker GPG key
    - name: get key
      shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"

    # Add Docker repo
    - name: Add docker ppa
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: yes

    # Install Docker
    - name: install docker
      apt:
        name: "{{item}}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-compose

    # Start Docker service
    - name: start docker service
      service:
        name: docker
        state: started
        enabled: true

    # Add user to docker group
    - name: adding existing user to group docker
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes