- name: Update Kubernetes Deployment Image (rentestate)
  hosts: appservers
  become: yes
  gather_facts: no

  vars:
    kubeconfig: "/home/azureuser/.kube/config"
    namespace: "rentestate"
    deployment_name: "rentestate-app"
    container_name: "app"
    new_image: "ghcr.io/skk137/rentestate2:latest"
    selector_label: "app=rentestate-app"

  pre_tasks:
    # Install Python and pip
    - name: Ensure Python and pip are installed
      apt:
        name:
          - python3-pip
          - python3-venv
        state: present
        update_cache: yes

    # Install Python deps for Kubernetes
    - name: Install required Python deps for Kubernetes
      apt:
        name:
          - python3-kubernetes
          - python3-openshift
        state: present

  tasks:
    # Show current image
    - name: Show current image (before)
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        kind: Deployment
        namespace: "{{ namespace }}"
        name: "{{ deployment_name }}"
      register: dep_before

    # Update image
    - name: Update the deployment image
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig }}"
        namespace: "{{ namespace }}"
        kind: Deployment
        name: "{{ deployment_name }}"
        definition:
          spec:
            template:
              spec:
                containers:
                  - name: "{{ container_name }}"
                    image: "{{ new_image }}"

    # Wait for rollout
    - name: Poll deployment status until all replicas are available
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        api_version: apps/v1
        kind: Deployment
        namespace: "{{ namespace }}"
        name: "{{ deployment_name }}"
      register: dep_status
      until: >
        (dep_status.resources | length) > 0 and
        (dep_status.resources[0].status.availableReplicas | default(0)) ==
        (dep_status.resources[0].spec.replicas | default(0))
      retries: 60
      delay: 6

    # Get pods
    - name: Get pods of this deployment
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        kind: Pod
        namespace: "{{ namespace }}"
        label_selectors:
          - "{{ selector_label }}"
      register: pod_list

    # Collect images from pods
    - name: Collect images of target container from running pods
      set_fact:
        container_images: "{{ pod_list.resources | json_query(query) | list }}"
      vars:
        query: "[?status.phase=='Running'].spec.containers[?name=='{{ container_name }}'].image[]"

    # Fail if wrong image
    - name: Fail if any running pod is NOT using the new image
      fail:
        msg: >-
          One or more pods do not run the expected image {{ new_image }}.
          Found images: {{ (container_images | unique) | join(', ') }}
      when: >
        ((container_images | unique) | difference([new_image])) | length > 0

    # Summary
    - name: Summary
      debug:
        msg:
          - "Updated deployment: {{ deployment_name }}"
          - "Container: {{ container_name }}"
          - "New image: {{ new_image }}"
          - "Pods using image: {{ (container_images | unique) | join(', ') }}"