---
# Deploy Spring Boot app with Nginx
- hosts: appservers

  pre_tasks:
    # Install Java
    - name: Install Java
      apt:
        name: openjdk-21-jdk
        state: present
        update_cache: yes
      become: yes

  tasks:
    # Debug appdir
    - name: "debug appdir"
      ansible.builtin.debug:
        msg: "appdir {{ansible_user_dir}}"

    # Clone Spring project
    - name: "Clone the Spring repository"
      git:
        repo: "https://github.com/skk137/rentEstate2.git"
        dest: "{{ appdir }}"
        version: "{{ branch }}"
        force: yes

    # Update application.properties
    - name: "Populate application.properties"
      lineinfile:
        dest: "{{ appdir }}/src/main/resources/application.properties"
        state: present
        regexp: "^{{item.key}}="
        line: "{{item.key}}={{item.value}}"
      with_items:
        - "{{app.env | dict2items}}"

    # Make mvnw executable
    - name: Ensure mvnw is executable
      file:
        path: "{{ appdir }}/mvnw"
        mode: '0755'

    # Build Spring app
    - name: "Build spring project"
      block:
        - name: "Build the Spring application"
          command: "./mvnw package -Dmaven.test.skip"
          args:
            chdir: "{{ appdir }}"

      rescue:
        - name: Fetch the SHA-512 checksum for Maven 3.9.9
          get_url:
            url: https://downloads.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.zip.sha512
            dest: /tmp/maven_sha512.txt
            validate_certs: yes
            force: yes

        - name: Read the SHA-512 checksum from the file
          command: cat /tmp/maven_sha512.txt
          register: sha512_checksum

        - name: Replace the distributionSha512Sum line in maven-wrapper.properties
          replace:
            path: "{{ appdir }}/.mvn/wrapper/maven-wrapper.properties"
            regexp: '^distributionSha'
            replace: "distributionSha512Sum={{ sha512_checksum.stdout }}"

        - name: Clean up the temporary file
          file:
            path: /tmp/maven_sha512.txt
            state: absent
          when: sha512_checksum is defined

      always:
        - name: "Build the Spring application"
          command: "./mvnw package -Dmaven.test.skip"
          args:
            chdir: "{{ appdir }}"

    # Copy systemd service
    - name: copy spring service file
      template:
        src: ../files/spring.service.j2
        dest: "/etc/systemd/system/spring.service"
      become: yes
      become_user: root
      notify: restart spring

    # Restart Spring service
    - name: reload spring service
      service:
        name: spring
        state: restarted
      become: yes

    # Ensure Spring service is enabled
    - name: ensure spring service started
      service:
        name: spring
        state: started
        enabled: yes
      become: yes

    # Install Nginx
    - name: "APT - install nginx"
      apt:
        name: nginx
        update_cache: yes
      become: yes

    # Copy Nginx config
    - name: copy nginx conf file
      template:
        src: ../files/nginx.http.j2
        dest: "/etc/nginx/sites-available/spring"
      become: yes

    # Enable Nginx site
    - name: enable spring site in nginx
      file:
        src: "/etc/nginx/sites-available/spring"
        dest: "/etc/nginx/sites-enabled/spring"
        state: link
      become: yes
      notify: restart nginx

    # Disable default Nginx site
    - name: de-activate default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      become: yes
      notify: restart nginx

  handlers:
    # Restart Spring
    - name: restart spring
      service:
        name: spring
        state: restarted
      become: yes

    # Restart Nginx
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes