---
- hosts: appservers

  pre_tasks:
    # Εγκαθιστά Java 21 απαραίτητη για Spring Boot app
    - name: Install Java
      apt:
        name: openjdk-21-jdk
        state: present
        update_cache: yes
      become: yes

  tasks:
    # Debug: εμφανίζει το appdir το οποίο χρήσιμο για troubleshooting
    - name: "debug appdir"
      ansible.builtin.debug:
        msg: "appdir {{ansible_user_dir}}"

    # Κάνει clone το Spring Boot project από GitHub
    - name: "Clone the Spring repository"
      git:
        repo: "https://github.com/skk137/rentEstate2.git"
        dest: "{{ appdir }}"
        version: "{{ branch }}"
        force: yes

    # Γράφει application.properties από variables του app.env
    - name: "Populate application.properties"
      lineinfile:
        dest: "{{ appdir }}/src/main/resources/application.properties"
        state: present
        regexp: "^{{item.key}}="
        line: "{{item.key}}={{item.value}}"
      with_items:
        - "{{app.env | dict2items}}"

    # Βεβαιώνεται ότι το mvnw script είναι εκτελέσιμο
    - name: Ensure mvnw is executable
      file:
        path: "{{ appdir }}/mvnw"
        mode: '0755'

    # Block: Προσπάθεια build με Maven και fallback σε checksum fix
    - name: "Build spring project"
      block:

        # Πρώτη προσπάθεια build
        - name: "Build the Spring application"
          command: "./mvnw package -Dmaven.test.skip"
          args:
            chdir: "{{ appdir }}"

      rescue:
        # Αν αποτύχει, κατεβάζει το SHA512 checksum του Maven
        - name: Fetch the SHA-512 checksum for Maven 3.9.9
          get_url:
            url: https://downloads.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.zip.sha512
            dest: /tmp/maven_sha512.txt
            validate_certs: yes
            force: yes

        # Διαβάζει το checksum
        - name: Read the SHA-512 checksum from the file
          command: cat /tmp/maven_sha512.txt
          register: sha512_checksum

        # Κάνει update το maven-wrapper.properties με το σωστό checksum
        - name: Replace the distributionSha512Sum line in maven-wrapper.properties
          replace:
            path: "{{ appdir }}/.mvn/wrapper/maven-wrapper.properties"
            regexp: '^distributionSha'
            replace: "distributionSha512Sum={{ sha512_checksum.stdout }}"

        # Σβήνει το προσωρινό αρχείο
        - name: Clean up the temporary file
          file:
            path: /tmp/maven_sha512.txt
            state: absent
          when: sha512_checksum is defined

      always:
        # Προσπαθεί ξανά το build πάντα
        - name: "Build the Spring application"
          command: "./mvnw package -Dmaven.test.skip"
          args:
            chdir: "{{ appdir }}"

    # Αντιγράφει το systemd unit file για την εφαρμογή
    - name: copy spring service file
      template:
        src: ../files/spring.service.j2
        dest: "/etc/systemd/system/spring.service"
      become: yes
      become_user: root
      notify: restart spring

    # Κάνει restart το Spring service για να πάρει αλλαγές
    - name: reload spring service
      service:
        name: spring
        state: restarted
      become: yes

    # Βεβαιώνεται ότι το Spring service τρέχει και ξεκινάει στο boot
    - name: ensure spring service started
      service:
        name: spring
        state: started
        enabled: yes
      become: yes

    # Εγκαθιστά Nginx με το reverse proxy
    - name: "APT - install nginx"
      apt:
        name: nginx
        update_cache: yes
      become: yes

    # Αντιγράφει το Nginx config
    - name: copy nginx conf file
      template:
        src: ../files/nginx.http.j2
        dest: "/etc/nginx/sites-available/spring"
      become: yes

    # Κάνει symlink το config στο sites-enabled
    - name: enable spring site in nginx
      file:
        src: "/etc/nginx/sites-available/spring"
        dest: "/etc/nginx/sites-enabled/spring"
        state: link
      become: yes
      notify: restart nginx

    # Απενεργοποιεί το default site του Nginx
    - name: de-activate default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      become: yes
      notify: restart nginx

  handlers:
    # Restart Spring service αν αλλάξει το systemd unit file
    - name: restart spring
      service:
        name: spring
        state: restarted
      become: yes

    # Restart Nginx για να φορτωθεί το νέο config
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes